ttitle 'Monitoring Dispatcher Performance'
SELECT NAME "NAME", SUBSTR(NETWORK,1,23) "PROTOCOL", OWNED, 
   2 STATUS "STATUS", (BUSY/(BUSY + IDLE)) * 100 "%TIME BUSY" 
   3 FROM V$DISPATCHER
/
ttitle 'Dispatcher Performance'
SELECT D.NAME, Q.QUEUED, Q.WAIT, Q.TOTALQ, 
       DECODE(Q.TOTALQ,0,0,(Q.WAIT/Q.TOTALQ)/100) "AVG WAIT" 
  FROM V$QUEUE Q, V$DISPATCHER D 
 WHERE D.PADDR = Q.PADDR
/ 
SELECT D.NAME, Q.QUEUED, Q.WAIT, Q.TOTALQ, 
       DECODE(Q.TOTALQ,0,0,(Q.WAIT/Q.TOTALQ)/100) "AVG WAIT" 
  FROM GV$QUEUE Q, GV$DISPATCHER D 
 WHERE D.PADDR = Q.PADDR
/ 
SELECT Q.TYPE, Q.QUEUED, Q.WAIT, Q.TOTALQ, 
       DECODE(Q.TOTALQ,0,0,(Q.WAIT/Q.TOTALQ)/100) "AVG WAIT" 
  FROM V$QUEUE Q 
 WHERE TYPE = 'COMMON'
/
title 'Setting Number of Shared Servers'
SELECT DECODE(TOTALQ, 0, 'No Requests', 
       WAIT/TOTALQ || ' HUNDREDTHS OF SECONDS') "AVERAGE WAIT TIME PER REQUESTS" 
  FROM V$QUEUE 
 WHERE TYPE = 'COMMON'
/
SELECT MAXIMUM_CONNECTIONS "MAX CONN", MAXIMUM_SESSIONS "MAX SESS", 
       SERVERS_STARTED "STARTED", SERVERS_TERMINATED "TERMINATED", 
       SERVERS_HIGHWATER "HIGHWATER" 
  FROM V$SHARED_SERVER_MONITOR
/

