SET LINESIZE 500
SET PAGESIZE 1000

COLUMN USERNAME FORMAT A18
COLUMN OSUSER FORMAT A18
COLUMN SPID FORMAT A10
COLUMN SERVICE_NAME FORMAT A15
COLUMN MODULE FORMAT A31
COLUMN MACHINE FORMAT A30
COLUMN LOGON_TIME FORMAT A20
COLUMN PGA_USED_MEM_MB FORMAT 99990.00
COLUMN PGA_ALLOC_MEM_MB FORMAT 99990.00
COLUMN PGA_FREEABLE_MEM_MB FORMAT 99990.00
COLUMN PGA_MAX_MEM_MB FORMAT 99990.00

BREAK ON REPORT
compute sum of PGA_USED_MB on report
compute sum of PGA_ALLOC_MB on report
compute sum of PGA_FREEABLE_MB on report
compute sum of PGA_MAX_MB on report

SELECT S.INST_ID,
       S.OSUSER,
       S.SID,
       S.SERIAL#,
       P.SPID,
       NVL(S.USERNAME, '(ORACLE)') AS USERNAME,
       TO_CHAR(S.LOGON_TIME,'DD-MON-YYYY HH24:MI:SS') AS LOGON_TIME,
	   S.STATUS,
       ROUND(P.PGA_USED_MEM/1024/1024,2) AS PGA_USED_MB,
       ROUND(P.PGA_ALLOC_MEM/1024/1024,2) AS PGA_ALLOC_MB,
       ROUND(P.PGA_FREEABLE_MEM/1024/1024,2) AS PGA_FREEABLE_MB,
       ROUND(P.PGA_MAX_MEM/1024/1024,2) AS PGA_MAX_MB,
       --S.LOCKWAIT,
       S.SERVICE_NAME,
       S.MODULE,
       S.MACHINE,
       --S.PROGRAM,
       S.LAST_CALL_ET AS LAST_CALL_ET_SECS
FROM   GV$SESSION S,
       GV$PROCESS P
WHERE  S.PADDR = P.ADDR
   AND S.USERNAME LIKE UPPER('%&USERNAME%') 
   AND S.INST_ID LIKE '%&INST_ID%' 
   AND S.SERVICE_NAME LIKE UPPER('%&SERVICE_NAME%') 
   AND S.MACHINE LIKE UPPER('%&MACHINE%') 
   AND S.SID LIKE '%&SID%' 
   AND S.STATUS LIKE UPPER('%&STATUS%')
ORDER BY 7 DESC;
